services:
  server:
    image: ubuntu
    container_name: teleport-server
    command: bash -c "apt update 
      && apt install -y curl
      && bash -c "$(curl -fsSL https://conductorone.teleport.sh/scripts/9fcced82c5ed07e4e045ca0e239f1771/install-node.sh)"
      && tail -F anything"
    restart: always

  tbot:
    image: ubuntu
    container_name: teleport-tbot
    environment:
      - TELEPORT_EDITION=enterprise
      - TELEPORT_VERSION=16.4.12

    volumes:
      - ./bot:/var/lib/teleport/bot

    command: bash -c "apt update
      && apt install -y curl
      && curl https://cdn.teleport.dev/install-v16.4.12.sh | bash -s $${TELEPORT_VERSION?} $${TELEPORT_EDITION?}
      && tail -F anything"
    restart: always
