package config

import "github.com/conductorone/baton-sdk/pkg/field"

var (
	TeleportKeyFilePathField = field.StringField(
		"teleport-key-path",
		field.WithDisplayName("Teleport Key Path"),
		field.WithDescription("Path to the teleport file generated by using the tctl admin tool. Example: \"auth.pem\"."),
	)
	TeleportKeyField = field.StringField(
		"teleport-key",
		field.WithDisplayName("Teleport Key"),
		field.WithDescription("The teleport key generated by using the tctl admin tool"),
	)
	ProxyAddressField = field.StringField(
		"teleport-proxy-address",
		field.WithDisplayName("Proxy Address"),
		field.WithRequired(true),
		field.WithDescription("The fully-qualified teleport proxy service to connect with. Example: \"baton.teleport.sh:443\"."),
	)

	fieldRelationships = []field.SchemaFieldRelationship{
		field.FieldsMutuallyExclusive(TeleportKeyFilePathField, TeleportKeyField),
		field.FieldsAtLeastOneUsed(TeleportKeyFilePathField, TeleportKeyField),
	}
)

//go:generate go run ./gen
var Config = field.NewConfiguration(
	[]field.SchemaField{
		ProxyAddressField,
		TeleportKeyFilePathField,
		TeleportKeyField,
	},
	field.WithConstraints(fieldRelationships...),
	field.WithConnectorDisplayName("Teleport"),
	field.WithHelpUrl("/docs/baton/teleport"),
	field.WithIconUrl("/static/app-icons/teleport.svg"),
)
