package config

import "github.com/conductorone/baton-sdk/pkg/field"

var (
	TeleportKeyFilePathField = field.StringField(
		"teleport-key-path",
		field.WithDescription("Path to the teleport file generated by using the tctl admin tool. Example: \"auth.pem\"."),
	)
	TeleportKeyField = field.StringField(
		"teleport-key",
		field.WithDescription("The teleport key generated by using the tctl admin tool"),
	)
	ProxyAddressField = field.StringField(
		"teleport-proxy-address",
		field.WithRequired(true),
		field.WithDescription("The fully-qualified teleport proxy service to connect with. Example: \"baton.teleport.sh:443\"."),
	)
	ConfigurationFields = []field.SchemaField{
		ProxyAddressField,
		TeleportKeyFilePathField,
		TeleportKeyField,
	}

	ConfigurationSchema = field.NewConfiguration(
		ConfigurationFields,
		field.FieldsMutuallyExclusive(TeleportKeyFilePathField, TeleportKeyField),
		field.FieldsAtLeastOneUsed(TeleportKeyFilePathField, TeleportKeyField),
	)
)
